@url_base = http://localhost:5231/dev/evento

### Cadastrar evento
POST {{url_base}}/cadastrar
Authorization: Bearer 
Content-Type: application/json

{
    "email" : "adm",
    "local" : "adm",
    "data" : "2025-02-02",
    "senha" : "123"
}

### Listar Eventos
GET {{url_base}}/listar
Authorization: Bearer

### Login
POST http://localhost:5231/dev/usuario/login
Content-Type: application/json

{
    "email" : "adm",
    "senha" : "123"
}

