@url_base = http://localhost:5231/dev/evento

### Cadastrar evento
POST {{url_base}}/cadastrar
Content-Type: application/json

{
    "email" : "adm",
    "local" : "adm",
    "data" : "adm",
    "senha" : "123"
}

### Listar usuários
GET {{url_base}}/listar
Authorization: Bearer

### Login
POST {http://localhost:5231/dev/usuario}/login
Content-Type: application/json

{
    "email" : "adm",
    "senha" : "123"
}

